### PR TITLE
Read the docs sphinx

### PR DESCRIPTION
**Pull request by og113**
This replaces PR #8. The difference is that here I am using sphinx, whereas there I used mkdocs, to build the docs. The advantage of sphinx, is that it is more similar to what is done on the WallGo repo, so it is easier to make the two align.

To see the docs built based on this branch: https://wallgocollision.readthedocs.io/en/readthedocssphinx

The basic setup is the following:
- a simple .readthedocs.yml file in the repo root, to tell ReadTheDocs what to do
- inside the docs/ directory there is now a Makefile which runs sphinx to build the static html docs. This can be run with `make html` from within the docs directory.
- docs source files are now inside docs/source
- the python file which has all the sphinx stuff in it is docs/source/conf.py

Some changes I have made:
- I have introduced bibtex references for papers
- I have linked to GitHub urls directly for the examples
- I have added some commands in the .md files e.g. build the table of contents/left hand menu
- I have added some pics, and a contact and License page, just like on the WallGo docs

There is still plenty more work that could be done to the docs, but I thought this was a reasonable place to start.

### CODE REVIEW

**Comment by jorindevandevis** [comment]
Thank you Oli, the pages look good and all the links that I clicked worked.

Here are some comments. I don't think they are all necessarily relevant to this PR per se, but let me list them anyway.

- There is a bit of a mismatch between the notation in the draft (e.g. eq 3.25), because the collision tensors in the draft now always have two species labels.
- Maybe add a reference to WallGoMatrix in the paragraph starting with  "The user must provide relevant particle content for their model, matrix elements  of their choice in a symbolic form"
- In the quickstart section: the grammatical structure of point 4 is a bit strange (sorry for nitpicking)
- Is there a file anywhere that is associated to the QuickStart section? If so, would be good to link to it.
- In quickstart: Here we define a “top quark” and a “gluon” as out-of-equilibrium particles, and a generic “light quark” that is kept in equilibrium. Maybe use capitals like in the code example, i.e. "Top" etc
- I am a bit confused about the function defineParameter. In the example files, we use. parameters.addOrModifyParameter (which should actually still be changed to parameters.add ) in the way that modelDef.definiteParameter is used in the docs. Has this changed recently?
- The installation page refers to quickstart for a quick installation instruction, but that's not yet there. Maybe add a TODO somewhere.
- Should the manually installing dependencies mention Windows?

**Comment by og113** [comment]
Jorinde's questions as a task list using the markdown `- [ ]`:

- [ ] There is a bit of a mismatch between the notation in the draft (e.g. eq 3.25), because the collision tensors in the draft now always have two species labels.
- [ ] Maybe add a reference to WallGoMatrix in the paragraph starting with "The user must provide relevant particle content for their model, matrix elements of their choice in a symbolic form"
- [ ] In the quickstart section: the grammatical structure of point 4 is a bit strange (sorry for nitpicking)
- [ ] Is there a file anywhere that is associated to the QuickStart section? If so, would be good to link to it.
- [ ] In quickstart: Here we define a “top quark” and a “gluon” as out-of-equilibrium particles, and a generic “light quark” that is kept in equilibrium. Maybe use capitals like in the code example, i.e. "Top" etc
- [ ] I am a bit confused about the function defineParameter. In the example files, we use. parameters.addOrModifyParameter (which should actually still be changed to parameters.add ) in the way that modelDef.definiteParameter is used in the docs. Has this changed recently?
- [ ] The installation page refers to quickstart for a quick installation instruction, but that's not yet there. Maybe add a TODO somewhere.
- [ ] Should the manually installing dependencies mention Windows?

**Comment by jorindevandevis** [comment]
Screenshot 2024-11-01 at 10 38 58

I think this blue box is supposed to end earlier, right? The ::: does not seem to do what it should.

**Comment by og113** [comment]
While not everything has been done here, I would be happy to put the remaining things in Issues to fix another day.

**Review by jorindevandevis — APPROVED** [review]
Sounds good, there were only a few small things left anyway. Overall the docs look very good.

**Pull request merged**
